# -*- coding: utf-8 -*-
"""NHS_RTTwaitingtimes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S69-fUzYvr9y8baZitE35bNZ3BQ6PC0l

**To analyze and understand patient waiting times across different NHS providers and treatments, identify delays, and suggest insights for improvement.**
"""

import pandas as pd

file_path = "/content/20250131-RTT-January-2025-full-extract.csv"

#load data
df = pd.read_csv(file_path)

#display first few rows
df.head()

"""Incomplete pathways (patients still waiting at the end of the month)

Admitted pathways (patients completed RTT with inpatient/day case admission)

Non-admitted pathways (patients completed RTT without admission)

Incomplete with decision to admit (patients waiting but with a decision to admit)

New RTT periods (newly started pathways during the month)

**DATA EXPLORATION**
"""

df.shape

"""*188209 rows*

*121 columns*
"""

df.columns #column names

"""**Key Columns**


*   Treatment Funtion Name -> to get what type of treatment
*   Commissioner Org Name/ Provider Org Code -> to explore regional differences
*   RTT Part Description -> to distinguish incomplete, admitted, non-admitted
*   All columns starting with Gt XX To YY Weeks SUM 1 → actual waiting times



"""

#shows data types and non-null values
df.info()

#gives count, mean,std, min, max for all numeric columns
df.describe()

#print unique values of a cloums
unique_values = df['Provider Parent Org Code'].unique()
print(unique_values)

#Print unique values for multiple columns
columns_to_check = ['Provider Parent Name',
       'Provider Org Code', 'Provider Org Name',
       'Commissioner Parent Org Code', 'Commissioner Parent Name',
       'Commissioner Org Code', 'Commissioner Org Name', 'RTT Part Type', 'RTT Part Description','Treatment Function Code','Treatment Function Name']
for col in columns_to_check:
    unique_values = df[col].unique()
    print(f"Unique values for {col}:")
    print(unique_values)
    print("\n")

#duplicates in a column
duplicates = df['Provider Parent Org Code'].duplicated()
print(duplicates)

"""The .duplicated() method checks whether each value in the column has already appeared earlier in the dataset.

False means this is the first time that value has appeared (i.e. it's the first occurrence).

True means this value has already been seen earlier — it’s a duplicate.

**DATA CLEANING**
"""

#to see the duplicated rows
df[df['Provider Parent Org Code'].duplicated()]

#null values
null_values = df.isnull().sum()
print(null_values)

#to find null value of a specific column
null_values = df['Gt 103 To 104 Weeks SUM 1'].isnull().sum()
print(null_values)

unique_values = df['Gt 103 To 104 Weeks SUM 1'].unique()
print(unique_values)

# Remove rows with null in critical columns
df = df.dropna(subset=['Provider Org Name', 'Treatment Function Name'])

"""dropna(): removes rows with null (NaN) values

subset=[...]: limits the check to only the specified columns

Keeps only the rows where both 'Provider Org Name' and 'Treatment Function Name' are not null

If either of those two columns is missing in a row, that row is dropped.
"""

df = df.drop(columns=['Period'])

# Define important columns
key_columns = [
    'Provider Org Name',
    'Commissioner Org Name',
    'Treatment Function Name',
    'RTT Part Description'
]

# Identify all waiting time columns
wait_columns = [col for col in df.columns if 'Weeks SUM 1' in col]
# Fill nulls in wait-time columns with 0 (assume no patients waited that long)
df[wait_columns] = df[wait_columns].fillna(0)

df['Total_calculated'] = df[wait_columns].sum(axis=1)

# Compare calculated total to existing 'Total'
comparison = (df['Total_calculated'] == df['Total'])
print("Matching totals:", comparison.sum(), "out of", len(df))

# Confirm structure
print("Shape after cleaning:", df.shape)
print("\nColumn data types:\n", df.dtypes.head(10))

"""Let’s identify what we are analyzing:

Wait time columns → e.g., "Gt 00 To 01 Weeks SUM 1" to "Gt 104 Weeks SUM 1"

Grouped by: Provider Org Name, Commissioner Org Name, Treatment Function Name

So, we are analyzing how long patients waited, and where (which hospital/region/treatment).

To find which NHS providers have the highest number of patients waiting, which aligns directly with your goal of identifying delays and regional differences
"""

# Total patients per Provider
provider_summary = df.groupby('Provider Org Name')['Total'].sum().sort_values(ascending=False)
print(provider_summary.head(10))

"""To find which Treatment functions have the highest number of patients waiting."""

# Total patients per Treatment Function
treatment_summary = df.groupby('Treatment Function Name')['Total'].sum().sort_values(ascending=False)
print(treatment_summary.head(10))

"""VISUALZATION"""

# Top 10 Providers
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(12, 6))
sns.barplot(x=provider_summary.head(10).values, y=provider_summary.head(10).index, palette='viridis')
plt.title('Top 10 NHS Providers by Total Patients Waiting')
plt.xlabel('Total Patients Waiting')
plt.ylabel('Provider')
plt.tight_layout()
plt.show()

# Distribution of Wait Times (Sum Across All Providers)
wait_time_summary = df[wait_columns].sum()
plt.figure(figsize=(18, 6))
wait_time_summary.plot(kind='line', marker='o')
plt.title("Distribution of Patient Wait Times (All Providers)")
plt.xlabel("Wait Time Ranges (Weeks)")
plt.ylabel("Number of Patients")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# Patients waiting over 52 weeks
df['Long Waiters'] = df[[col for col in wait_columns if '52' in col or '53' in col or '54' in col]].sum(axis=1)
long_wait_summary = df.groupby('Provider Org Name')['Long Waiters'].sum().sort_values(ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x=long_wait_summary.head(10).values, y=long_wait_summary.head(10).index, palette='magma')
plt.title('Top 10 Providers with Most Long Waiting Patients (>52 Weeks)')
plt.xlabel('Patients Waiting >52 Weeks')
plt.ylabel('Provider')
plt.tight_layout()
plt.show()

region_summary = df.groupby('Provider Parent Name')['Total_calculated'].sum().sort_values(ascending=False)

#Sort and select top 10 or all if it's not too crowded
top_regions = region_summary.head(10)  # or use region_summary for all

plt.figure(figsize=(12, 6))
sns.barplot(x=top_regions.values, y=top_regions.index, palette='coolwarm')
plt.title('Top Regions by Total Patients Waiting')
plt.xlabel('Total Patients Waiting')
plt.ylabel('Region (Provider Parent Name)')
plt.tight_layout()
plt.show()

df['Long Waiters'] = df[[col for col in wait_columns if '52' in col or '53' in col or '54' in col]].sum(axis=1)
long_wait_summary = df.groupby('Provider Org Name')['Long Waiters'].sum().sort_values(ascending=False)

# Sort values to get top 10 providers with longest waits
top_long_waits = long_wait_summary.head(10)

# Plot
plt.figure(figsize=(12, 6))
sns.barplot(x=top_long_waits.values, y=top_long_waits.index, palette='magma')
plt.title('Top 10 Providers with Longest Waiting Patients (>52 Weeks)')
plt.xlabel('Number of Long Waiters (>52 Weeks)')
plt.ylabel('Provider Name')
plt.tight_layout()
plt.show()

"""# Task
Analyze the waiting times for different RTT Part Types to identify which types have the longest waiting times and in which waiting time categories these delays are most prominent.

## Group data by rtt part type

### Subtask:
Group the DataFrame by the 'RTT Part Type' column and sum the waiting time columns to get the total number of patients in each waiting time category for each RTT Part Type.

**Reasoning**:
Group the dataframe by 'RTT Part Type' and sum the waiting time columns.
"""

rtt_wait_time_summary = df.groupby('RTT Part Type')[wait_columns].sum()

"""**Reasoning**:
The DataFrame `df` was not defined in the current session, so I need to reload the data and perform the necessary cleaning steps again before grouping and summing the waiting time columns.


"""

import pandas as pd

file_path = "/content/20250131-RTT-January-2025-full-extract.csv"

#load data
df = pd.read_csv(file_path)

# Remove rows with null in critical columns
df = df.dropna(subset=['Provider Org Name', 'Treatment Function Name'])

df = df.drop(columns=['Period'])

# Identify all waiting time columns
wait_columns = [col for col in df.columns if 'Weeks SUM 1' in col]
# Fill nulls in wait-time columns with 0 (assume no patients waited that long)
df[wait_columns] = df[wait_columns].fillna(0)

# Group the DataFrame by the 'RTT Part Type' column and sum the waiting time columns
rtt_wait_time_summary = df.groupby('RTT Part Type')[wait_columns].sum()

"""## Visualize waiting times per rtt part type

### Subtask:
Create visualizations (e.g., stacked bar charts or line plots) to compare the distribution of waiting times across different RTT Part Types.

**Reasoning**:
Transpose the RTT waiting time summary and create a stacked bar chart to visualize the distribution of waiting times by RTT Part Type, adding appropriate labels, title, and legend.
"""

# Transpose the DataFrame
rtt_wait_time_summary_T = rtt_wait_time_summary.T

# Create a stacked bar chart
plt.figure(figsize=(18, 10))
rtt_wait_time_summary_T.plot(kind='bar', stacked=True, figsize=(18, 10))

# Add title and labels
plt.title('Distribution of Patient Waiting Times by RTT Part Type')
plt.xlabel('Wait Time Ranges (Weeks)')
plt.ylabel('Number of Patients')
plt.xticks(rotation=90)
plt.legend(title='RTT Part Type')
plt.tight_layout()

# Display the plot
plt.show()

"""## Identify key insights

### Subtask:
Analyze the visualizations to identify which RTT Part Types have the longest waiting times and in which waiting time categories these delays are most prominent.

## Summary:

### Data Analysis Key Findings

*   Certain RTT Part Types, specifically "First Attendances", "Subsequent Attendances", and "Unclassified Activity", consistently contribute a larger number of patients to waiting lists across most waiting time categories.
*   In the longer waiting time categories (18+ weeks and 52+ weeks), "First Attendances" and "Subsequent Attendances" represent a substantial portion of the patients, indicating that delays are most prominent for these RTT Part Types.
*   "Admissions" and "Non Admitted Activity" generally have fewer patients experiencing extremely long waits compared to the attendance categories.

### Insights or Next Steps

*   Prioritize strategies to reduce waiting times for "First Attendances" and "Subsequent Attendances" as they contribute the most to long waits.
*   Investigate the reasons behind the significant number of patients in "Unclassified Activity" and aim to reclassify or address these cases to potentially improve waiting time management.
"""
